# Site Settings


# Name of your site (displayed in the header)
myname: Nihal Singh
alias: nihal111
# Short bio or description (displayed in the header)
byline: I like to know things

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars1.githubusercontent.com/u/13916513?v=2&s=460


# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: nihal111
  instagram:
  linkedin: nihal111
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: 
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: nihal111

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: "http://nihal111.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""


title: Nihal Singh
email: nihaliter@gmail.com
description: >
  Nihal Singh's personal blog.

github_username:  nihal111
facebook_username: Nihal Singh
linkedin_username:  Nihal Singh
facebook_id: nihal111
linkedin_id: nihal111
address: Indian Institue of Technology, Bombay Mumbai-400076, India
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
